#!/bin/env bash

py_file=$1

if [[ -e $py_file ]]; then
  echo -ne "File $py_file exist.\ndo you want to delete file?(yY|nN) "
  read -r opt
  [[ $opt =~ y|Y(es)? ]] && rm -rf "$py_file"; exit 34
  [[ $opt =~ n|N(o)? ]] && exit 35
elif [[ -z $py_file ]]; then
  echo "Please provide file name"; exit 128
else touch "$py_file"
fi


cat  > "$py_file" <<-PYCODE
#!/bin/env python3

# user -> $(whoami)
# date -> $(date "+%a-%b-%Y  %T")

import os
import sys


def main():
    pass


if __name__ == '__main__':
    main()
PYCODE

[[ -e $py_file ]] && chmod u+x "$py_file"
