#!/bin/env bash

# user -> u0_a271
# file -> music_format
# date -> Thu-Jun-2022  15:03:30
shopt -s globstar

for music in **/*.mp3; do
  declare bitrate=$(ffprobe -show_format 2>/dev/null "$music" | grep bit_rate | awk -F= '{ print $2 }')
  if [[ "$bitrate" != "N/A" ]]; then
    declare -i rate=$(( bitrate / 1000 ))
    if (( rate < 250 )); then
      echo "$music" >> ./deleted_file.txt
      rm -rf "$music"
    fi
  fi
done
