#!/bin/env bash
## pnpm setup react
echo "setting up react app.."
pnpm create vite@latest "$1" --template react-ts

cd "$1" || exit

## setup tailwindcss
echo "setting up tailwindcss.."
pnpm install -D tailwindcss postcss autoprefixer

cat > ./tailwind.config.cjs << EOF
module.exports = {
  darkMode: 'class',
  content: ['./index.html','./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      backgroundImage: {},
      colors: {
        primary: {
        },
        light: {
        },
        dark: {
        },
      },
    },
    fontFamily: {
      sans: ['Inter'],
    },
  },
  plugins: [],
};
EOF

cat > .eslintrc.json << EOF
{
    "parserOptions":{
        "sourceType": "module",
        "ecmaVersion": 13,
        "ecmaFeatures": {
            "jsx": true,
            "modules": true,
            "experimentalObjectRestSpread": true
        }
    },
    "plugins":["react"],
    "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:react/jsx-runtime"],
    "root": true,
    "env": {
        "browser": true,
        "es2022": true,
        "node": true
    }
}
EOF

cat > ./postcss.config.cjs << EOF
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    ...(process.env.NODE_ENV === 'production' ? { cssnano: {} } : {})
  }
}
EOF

cat > ./jsconfig.json << EOF
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Node",
    "target": "ES2020",
    "jsx": "react",
    "strictNullChecks": true,
    "strictFunctionTypes": true
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ]
}
EOF

cat > ./src/index.css << EOF
@tailwind base;
@tailwind components;
@tailwind utilities;
EOF

echo "setup react-router-dom && react-query.."

pnpm install react-router-dom localforage match-sorter sort-by
pnpm install react-query

cat > ./src/main.tsx << EOF
import React from 'react';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import { QueryClient, QueryClientProvider } from 'react-query';
const router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
  },
]);

const queryClient = new QueryClient();

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </React.StrictMode>
);
EOF

pnpm install

echo "Finish setup"
